apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <kasisnu@someexample.org>
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: dns
          digitalocean:
            tokenSecretRef:
              name: digitalocean-secrets
              key: DO_TOKEN
